#!/usr/bin/env python3
"""Refuse to commit anything that looks like a real bank statement.

This project's premise is that your statements never leave your machine, and
the easiest way to break that promise is an absent-minded ``git add .`` in the
folder you were testing against. This hook is the backstop.

It is deliberately conservative: it inspects file *contents* rather than trusting
names, because ``notes.csv`` in a downloads folder is just as likely to be a
statement as ``statement.csv`` is. Files under ``tests/fixtures/`` are exempt —
they are generated by a seeded script and contain no real data.

Run directly to check specific files::

    python scripts/check_no_real_data.py path/to/file.csv
"""

from __future__ import annotations

import csv
import io
import re
import sys
from pathlib import Path

EXEMPT_PREFIXES = ("tests/fixtures/",)
SUSPICIOUS_SUFFIXES = {".csv", ".tsv", ".txt", ".ofx", ".qfx", ".qif"}

# Header cells that, together, mean "this is a ledger".
_DATE_WORDS = re.compile(r"\b(date|datum|fecha|buchungstag)\b", re.I)
_MONEY_WORDS = re.compile(
    r"\b(amount|debit|credit|balance|paid (in|out)|withdrawal|deposit|betrag|montant)\b",
    re.I,
)
_DESC_WORDS = re.compile(
    r"\b(description|payee|merchant|narrative|details|memo|particulars|verwendungszweck)\b",
    re.I,
)

# Strings that are almost never in synthetic data.
_ACCOUNT_NUMBER = re.compile(r"\b\d{8,}\b")
_IBAN = re.compile(r"\b[A-Z]{2}\d{2}[A-Z0-9]{10,30}\b")
_CARD = re.compile(r"\b(?:\d[ -]?){13,19}\b")


def _is_exempt(path: str) -> bool:
    normalized = path.replace("\\", "/")
    return any(normalized.startswith(prefix) for prefix in EXEMPT_PREFIXES)


def looks_like_a_statement(path: Path) -> str | None:
    """Return a reason string if ``path`` looks like real financial data."""
    if path.suffix.lower() in {".ofx", ".qfx", ".qif"}:
        return "banking interchange format"

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None

    head = "\n".join(text.splitlines()[:30])
    if not head.strip():
        return None

    has_ledger_header = bool(
        _DATE_WORDS.search(head) and _MONEY_WORDS.search(head) and _DESC_WORDS.search(head)
    )
    if not has_ledger_header:
        return None

    # A ledger-shaped header alone is not proof — this repo is full of test
    # data and documentation examples. Look for identifiers too.
    for pattern, label in (
        (_IBAN, "what looks like an IBAN"),
        (_CARD, "what looks like a card number"),
        (_ACCOUNT_NUMBER, "a long numeric identifier"),
    ):
        match = pattern.search(head)
        if match:
            return f"transaction-shaped columns and {label} ({match.group()[:4]}…)"

    try:
        rows = list(csv.reader(io.StringIO(text)))
    except csv.Error:
        return None
    if len(rows) > 200:
        return "transaction-shaped columns and a large number of rows"

    return None


def main(argv: list[str]) -> int:
    findings: list[tuple[str, str]] = []
    for arg in argv:
        if _is_exempt(arg):
            continue
        path = Path(arg)
        if not path.is_file() or path.suffix.lower() not in SUSPICIOUS_SUFFIXES:
            continue
        reason = looks_like_a_statement(path)
        if reason:
            findings.append((arg, reason))

    if not findings:
        return 0

    print("Refusing to commit: these files look like real financial data.\n")
    for name, reason in findings:
        print(f"  {name}\n      {reason}")
    print(
        "\nIf this is synthetic test data, put it under tests/fixtures/ or commit "
        "with --no-verify.\nIf it is a real statement, it does not belong in git."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
